/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author MARCOS
 */
public class TelaAtividade1 extends javax.swing.JFrame {

    /**
     * Creates new form TelaAtividade1
     */
    public TelaAtividade1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTituloAtv = new javax.swing.JLabel();
        jLabelDisciplinas = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabelAlunosOrientados = new javax.swing.JLabel();
        jRadioButtonAlunosDoutorado = new javax.swing.JRadioButton();
        jRadioButtonAlunosMestrado = new javax.swing.JRadioButton();
        jRadioButtonAlunosIniciacao = new javax.swing.JRadioButton();
        jLabelArtigosPub = new javax.swing.JLabel();
        jButtonUploadArtigo = new javax.swing.JButton();
        jRadioButtonAlunosGraduacao = new javax.swing.JRadioButton();
        jLabelAtivCoord = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jButtonAtualizar = new javax.swing.JButton();
        jLabelFundoDescricao = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAjudaProf = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuSairProf = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabelTituloAtv.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabelTituloAtv.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTituloAtv.setText("Descrição de Atividade");
        getContentPane().add(jLabelTituloAtv);
        jLabelTituloAtv.setBounds(40, 30, 230, 50);
        jLabelTituloAtv.getAccessibleContext().setAccessibleName("Atividade 1 ");

        jLabelDisciplinas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelDisciplinas.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDisciplinas.setText("Disciplina:");
        getContentPane().add(jLabelDisciplinas);
        jLabelDisciplinas.setBounds(70, 90, 90, 40);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Técnicas Avançadas em Programação" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(150, 100, 310, 20);

        jLabelAlunosOrientados.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelAlunosOrientados.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAlunosOrientados.setText("Alunos Orientados:");
        getContentPane().add(jLabelAlunosOrientados);
        jLabelAlunosOrientados.setBounds(70, 150, 140, 30);

        jRadioButtonAlunosDoutorado.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonAlunosDoutorado.setText("Alunos de Doutorado");
        getContentPane().add(jRadioButtonAlunosDoutorado);
        jRadioButtonAlunosDoutorado.setBounds(200, 280, 180, 23);

        jRadioButtonAlunosMestrado.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonAlunosMestrado.setText("Alunos de Mestrado");
        getContentPane().add(jRadioButtonAlunosMestrado);
        jRadioButtonAlunosMestrado.setBounds(200, 240, 180, 23);

        jRadioButtonAlunosIniciacao.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonAlunosIniciacao.setSelected(true);
        jRadioButtonAlunosIniciacao.setText("Alunos de Graduação - Iniciação Científica");
        getContentPane().add(jRadioButtonAlunosIniciacao);
        jRadioButtonAlunosIniciacao.setBounds(200, 200, 260, 23);

        jLabelArtigosPub.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelArtigosPub.setForeground(new java.awt.Color(255, 255, 255));
        jLabelArtigosPub.setText("Artigos Publicados:");
        getContentPane().add(jLabelArtigosPub);
        jLabelArtigosPub.setBounds(70, 340, 140, 30);

        jButtonUploadArtigo.setText("artigo-tap.pdf");
        jButtonUploadArtigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUploadArtigoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonUploadArtigo);
        jButtonUploadArtigo.setBounds(210, 340, 170, 30);

        jRadioButtonAlunosGraduacao.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonAlunosGraduacao.setText("Alunos de Graduação - TCC");
        jRadioButtonAlunosGraduacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAlunosGraduacaoActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonAlunosGraduacao);
        jRadioButtonAlunosGraduacao.setBounds(200, 160, 180, 23);

        jLabelAtivCoord.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelAtivCoord.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAtivCoord.setText("Atividades de Coordenação:");
        getContentPane().add(jLabelAtivCoord);
        jLabelAtivCoord.setBounds(70, 400, 190, 20);

        jEditorPane1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jEditorPane1.setText("No decorrer do semestre desenvolvemos atividades com ênfase na linguagem de programação Java. \nAprimoramos conhecimentos aprendendo a inicializar projetos em base da realidade atual de determinadas situações de diversas profissões.");
        jScrollPane1.setViewportView(jEditorPane1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(250, 400, 350, 150);

        jButtonAtualizar.setBackground(new java.awt.Color(0, 153, 0));
        jButtonAtualizar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonAtualizar.setText("Atualizar");
        jButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAtualizar);
        jButtonAtualizar.setBounds(300, 600, 120, 40);

        jLabelFundoDescricao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoficial.png"))); // NOI18N
        getContentPane().add(jLabelFundoDescricao);
        jLabelFundoDescricao.setBounds(0, -40, 680, 930);

        jMenuAjudaProf.setText("Opções");

        jMenuItem1.setText("Voltar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuAjudaProf.add(jMenuItem1);

        jMenuBar1.add(jMenuAjudaProf);

        jMenuSairProf.setText("Sair");

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuSairProf.add(jMenuItemSair);

        jMenuBar1.add(jMenuSairProf);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonAlunosGraduacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAlunosGraduacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonAlunosGraduacaoActionPerformed

    private void jButtonUploadArtigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUploadArtigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUploadArtigoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        TelaProfessor telavoltarprof = new TelaProfessor ();
        telavoltarprof.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        TelaLogin telasair1 = new TelaLogin ();
        telasair1.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarActionPerformed
       TelaProfessor telaProf = new TelaProfessor();
       telaProf.setVisible(true);
       dispose();
    }//GEN-LAST:event_jButtonAtualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAtividade1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAtividade1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAtividade1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAtividade1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAtividade1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizar;
    private javax.swing.JButton jButtonUploadArtigo;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabelAlunosOrientados;
    private javax.swing.JLabel jLabelArtigosPub;
    private javax.swing.JLabel jLabelAtivCoord;
    private javax.swing.JLabel jLabelDisciplinas;
    private javax.swing.JLabel jLabelFundoDescricao;
    private javax.swing.JLabel jLabelTituloAtv;
    private javax.swing.JMenu jMenuAjudaProf;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenu jMenuSairProf;
    private javax.swing.JRadioButton jRadioButtonAlunosDoutorado;
    private javax.swing.JRadioButton jRadioButtonAlunosGraduacao;
    private javax.swing.JRadioButton jRadioButtonAlunosIniciacao;
    private javax.swing.JRadioButton jRadioButtonAlunosMestrado;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
