/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import ClassesDAO.DescricaoDAO;
import ClassesDAO.DocenteDAO;
import classes.Descricao;
import classes.Docente;
import java.util.Vector;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MARCOS
 */
public class TelaDescricao extends javax.swing.JFrame {

    Docente docente = new Docente();
    DocenteDAO docenteDAO = new DocenteDAO();
    Descricao descricao= new Descricao();
    DescricaoDAO descricaoDAO= new DescricaoDAO();

    /**
     * Creates new form TelaDescricaoRit
     */
    public TelaDescricao() {
        initComponents();
        listaTodos();
        
    }

    public void listaTodos() {

        Vector<Descricao> listaNomes = descricaoDAO.mostrarDescricao();
        Vector conjuntoLinhas = new Vector();

        for (Descricao con : listaNomes) {
            Vector linha = new Vector();
            linha.add(con.getNomeDisciplina());
            linha.add(con.getNomeDoArtigo());
            linha.add(con.getTipoDeOrientacao());
            linha.add(con.getDescricaoCoordenacao());

            conjuntoLinhas.add(linha);

        }
        Vector conjuntoColunas = new Vector();
        conjuntoColunas.add("NOME DISCIPLINA");
        conjuntoColunas.add("NOME DO ARTIGO");
        conjuntoColunas.add("TIPO");
        conjuntoColunas.add("DESCRIÇÃO");

        DefaultTableModel tabela = new DefaultTableModel(conjuntoLinhas, conjuntoColunas);

        jTableDescricao.setModel(tabela);

        jTableDescricao.getColumnModel().getColumn(0).setResizable(false);
        jTableDescricao.getColumnModel().getColumn(1).setResizable(false);
        jTableDescricao.getColumnModel().getColumn(2).setResizable(false);
        jTableDescricao.getColumnModel().getColumn(3).setResizable(false);
        //jTableListaConsulta.getColumnModel().getColumn(4).setResizable(false);

        jTableDescricao.getTableHeader().setReorderingAllowed(false);
        jTableDescricao.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelInfoRit = new javax.swing.JLabel();
        jButtonVoltar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDescricao = new javax.swing.JTable();
        jLabelFundoDescricao = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAjudaProf = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuSairProf = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabelInfoRit.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabelInfoRit.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInfoRit.setText("Informações Relatório Individual de Trabalho - RIT");
        getContentPane().add(jLabelInfoRit);
        jLabelInfoRit.setBounds(40, 20, 550, 40);

        jButtonVoltar.setBackground(new java.awt.Color(255, 102, 0));
        jButtonVoltar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltar);
        jButtonVoltar.setBounds(50, 470, 110, 40);

        jTableDescricao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableDescricao.setEnabled(false);
        jScrollPane2.setViewportView(jTableDescricao);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(50, 70, 590, 360);

        jLabelFundoDescricao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoficial.png"))); // NOI18N
        getContentPane().add(jLabelFundoDescricao);
        jLabelFundoDescricao.setBounds(-20, 0, 730, 710);

        jMenuAjudaProf.setText("Opções");

        jMenuItem1.setText("Voltar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuAjudaProf.add(jMenuItem1);

        jMenuBar1.add(jMenuAjudaProf);

        jMenuSairProf.setText("Sair");

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuSairProf.add(jMenuItemSair);

        jMenuBar1.add(jMenuSairProf);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(719, 616));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        TelaLogin telasair1 = new TelaLogin();
        telasair1.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        TelaPrincipal telaVoltar = new TelaPrincipal();
        telaVoltar.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDescricao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDescricao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDescricao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDescricao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDescricao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabelFundoDescricao;
    private javax.swing.JLabel jLabelInfoRit;
    private javax.swing.JMenu jMenuAjudaProf;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenu jMenuSairProf;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableDescricao;
    // End of variables declaration//GEN-END:variables
}
