/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import ClassesDAO.DisciplinasDAO;
import ClassesDAO.DocenteDAO;
import classes.Disciplinas;
import classes.Docente;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author MARCOS
 */
public class TelaCadastraDisciplina extends javax.swing.JFrame {

    /**
     * Creates new form TelaDescricaoRit
     */
    Docente docente = new Docente();
    DocenteDAO docenteDAO = new DocenteDAO();
    Disciplinas disciplinas = new Disciplinas();
    DisciplinasDAO disciplinasDAO = new DisciplinasDAO();
    Vector<Docente> listaDocente = null;
    int cod = 0;

    public TelaCadastraDisciplina() {
        initComponents();
        listaDocente = docenteDAO.mostrarDocente();
        DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel(listaDocente);
        jComboBoxProfessor.setModel(modeloCombo);
        jComboBoxProfessor.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelInfoRit = new javax.swing.JLabel();
        jLabelDisciplinas = new javax.swing.JLabel();
        jComboBoxProfessor = new javax.swing.JComboBox<>();
        jComboBoxDisciplinas = new javax.swing.JComboBox<>();
        jButtonAddDisciplina = new javax.swing.JButton();
        jLabelAlunosOrientados = new javax.swing.JLabel();
        jButtonVoltar = new javax.swing.JButton();
        jLabelFundoDescricao = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAjudaProf = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuSairProf = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabelInfoRit.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabelInfoRit.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInfoRit.setText("Disciplina - Professor");
        getContentPane().add(jLabelInfoRit);
        jLabelInfoRit.setBounds(40, 20, 550, 40);

        jLabelDisciplinas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelDisciplinas.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDisciplinas.setText("Disciplinas:");
        getContentPane().add(jLabelDisciplinas);
        jLabelDisciplinas.setBounds(60, 80, 90, 40);

        jComboBoxProfessor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxProfessorItemStateChanged(evt);
            }
        });
        jComboBoxProfessor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxProfessorMouseClicked(evt);
            }
        });
        getContentPane().add(jComboBoxProfessor);
        jComboBoxProfessor.setBounds(150, 130, 510, 30);

        jComboBoxDisciplinas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<< Selecione uma das opções >>", "Arquitetura de Computares", "Algoritmos e Estruturas de Dados I", "Algoritmos e Estruturas de Dados II", "Análise e Projetos de Sistemas", "Avaliação de Desempenho", "Banco de Dados I", "Computação Númerica", "Compiladores", "Empreendedorismo em Informática", "Introdução a Computação", "Introdução a Engenharia de Software", "Introdução a Teoria de Grafos", "Inteligência Artificial ", "Introdução a Computação Gráfica", "Interação Humano-Computador", "Informática Ética e Sociedade", "Laboratório de Programção Avançada", "Linguagem Formais e Automatos", "Matemática Discreta", "Metodologia Cientifica em Ciência da Computação", "Organização de Computadores", "Paradigmas de Linguagem de Programação", "Projeto e Análise de Algoritmos", "Programação Web", "Redes de Computadores", "Sistemas Lógicos", "Sistemas Operacionais", "Técnicas Avançadas de Programação", "Textos Técnicos em Ciencia da Computação " }));
        jComboBoxDisciplinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDisciplinasActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxDisciplinas);
        jComboBoxDisciplinas.setBounds(150, 90, 290, 20);

        jButtonAddDisciplina.setBackground(new java.awt.Color(0, 153, 0));
        jButtonAddDisciplina.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonAddDisciplina.setText("Salvar");
        jButtonAddDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddDisciplinaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAddDisciplina);
        jButtonAddDisciplina.setBounds(460, 230, 110, 40);

        jLabelAlunosOrientados.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelAlunosOrientados.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAlunosOrientados.setText("Professor:");
        getContentPane().add(jLabelAlunosOrientados);
        jLabelAlunosOrientados.setBounds(60, 130, 150, 30);

        jButtonVoltar.setBackground(new java.awt.Color(255, 102, 0));
        jButtonVoltar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltar);
        jButtonVoltar.setBounds(130, 230, 110, 40);

        jLabelFundoDescricao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoficial.png"))); // NOI18N
        jLabelFundoDescricao.setPreferredSize(new java.awt.Dimension(900, 956));
        getContentPane().add(jLabelFundoDescricao);
        jLabelFundoDescricao.setBounds(0, 0, 710, 320);

        jMenuAjudaProf.setText("Opções");

        jMenuItem1.setText("Voltar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuAjudaProf.add(jMenuItem1);

        jMenuBar1.add(jMenuAjudaProf);

        jMenuSairProf.setText("Sair");

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuSairProf.add(jMenuItemSair);

        jMenuBar1.add(jMenuSairProf);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(715, 370));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxDisciplinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDisciplinasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxDisciplinasActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        TelaLogin telasair1 = new TelaLogin();
        telasair1.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jButtonAddDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddDisciplinaActionPerformed
        if (jComboBoxDisciplinas.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Selecione a disciplina");
        } else if (cod <= 0) {
            JOptionPane.showMessageDialog(null, "Selecione o professor");

        } else {
            disciplinas.setSiape(cod);
            disciplinas.setNome(String.valueOf(jComboBoxDisciplinas.getSelectedItem()));
            if (disciplinasDAO.salvarDisciplinas(disciplinas) == true) {
                new TelaPrincipal().setVisible(true);
                dispose();
            } else {
                new TelaCadastraDisciplina().setVisible(true);
                dispose();
            }
        }
    }//GEN-LAST:event_jButtonAddDisciplinaActionPerformed

    private void jComboBoxProfessorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxProfessorMouseClicked
        // TODO add your handling code here:
        if (jComboBoxProfessor.getSelectedIndex() >= 0) {
            String nome = "" + jComboBoxProfessor.getModel().getSelectedItem();
            cod = docenteDAO.buscarDocente(nome);
            System.out.println(cod);

        }
    }//GEN-LAST:event_jComboBoxProfessorMouseClicked

    private void jComboBoxProfessorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxProfessorItemStateChanged
        // TODO add your handling code here:
        if (jComboBoxProfessor.getSelectedIndex() >= 0) {
            String nome = "" + jComboBoxProfessor.getModel().getSelectedItem();
            cod = docenteDAO.buscarDocente(nome);
            System.out.println(cod);

        }
    }//GEN-LAST:event_jComboBoxProfessorItemStateChanged

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        TelaPrincipal telaVoltar = new TelaPrincipal();
        telaVoltar.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastraDisciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastraDisciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastraDisciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastraDisciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastraDisciplina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddDisciplina;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JComboBox<String> jComboBoxDisciplinas;
    private javax.swing.JComboBox<String> jComboBoxProfessor;
    private javax.swing.JLabel jLabelAlunosOrientados;
    private javax.swing.JLabel jLabelDisciplinas;
    private javax.swing.JLabel jLabelFundoDescricao;
    private javax.swing.JLabel jLabelInfoRit;
    private javax.swing.JMenu jMenuAjudaProf;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenu jMenuSairProf;
    // End of variables declaration//GEN-END:variables
}
