/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import ClassesDAO.DocenteDAO;
import classes.Docente;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MARCOS
 */
public class TelaPrincipal extends javax.swing.JFrame {

    Docente docente = new Docente();
    DocenteDAO docenteDAO = new DocenteDAO();
    String nome = "";

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        listaTodos();
    }

    public void listaTodos() {

        Vector<Docente> listaNomes = docenteDAO.mostraTodosProfessores();
        Vector conjuntoLinhas = new Vector();

        for (Docente con : listaNomes) {
            Vector linha = new Vector();
            linha.add(con.getIdSiape());
            linha.add(con.getNome());
            linha.add(con.getEmail());

            conjuntoLinhas.add(linha);

        }
        Vector conjuntoColunas = new Vector();
        conjuntoColunas.add("ID");
        conjuntoColunas.add("NOME");
        conjuntoColunas.add("EMAIL");

        DefaultTableModel tabela = new DefaultTableModel(conjuntoLinhas, conjuntoColunas);

        jTableDocente.setModel(tabela);

        jTableDocente.getColumnModel().getColumn(0).setResizable(false);
        jTableDocente.getColumnModel().getColumn(1).setResizable(false);
        jTableDocente.getColumnModel().getColumn(2).setResizable(false);
        //jTableListaConsulta.getColumnModel().getColumn(3).setResizable(false);
        //jTableListaConsulta.getColumnModel().getColumn(4).setResizable(false);

        jTableDocente.getTableHeader().setReorderingAllowed(false);
        jTableDocente.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonAddProfessor = new javax.swing.JButton();
        jButtonAlterarProfessor = new javax.swing.JButton();
        jButtonSelecionar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButtonRemoverProfessor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDocente = new javax.swing.JTable();
        jLabelFundoPrincipal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAjuda = new javax.swing.JMenu();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Corpo Docente");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 20, 200, 20);

        jButtonAddProfessor.setBackground(new java.awt.Color(0, 153, 0));
        jButtonAddProfessor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonAddProfessor.setText("Adicionar");
        jButtonAddProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddProfessorActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAddProfessor);
        jButtonAddProfessor.setBounds(120, 420, 110, 50);

        jButtonAlterarProfessor.setBackground(new java.awt.Color(255, 102, 0));
        jButtonAlterarProfessor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonAlterarProfessor.setText("Alterar");
        jButtonAlterarProfessor.setEnabled(false);
        jButtonAlterarProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarProfessorActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAlterarProfessor);
        jButtonAlterarProfessor.setBounds(310, 420, 100, 50);

        jButtonSelecionar.setText("Selecionar");
        jButtonSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelecionarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSelecionar);
        jButtonSelecionar.setBounds(50, 370, 109, 25);

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Gerar Relatório");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(580, 420, 140, 50);

        jButtonRemoverProfessor.setBackground(new java.awt.Color(255, 0, 0));
        jButtonRemoverProfessor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonRemoverProfessor.setText("Remover");
        jButtonRemoverProfessor.setEnabled(false);
        jButtonRemoverProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverProfessorActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRemoverProfessor);
        jButtonRemoverProfessor.setBounds(440, 420, 100, 50);

        jTableDocente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableDocente);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 70, 720, 280);

        jLabelFundoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoficial.png"))); // NOI18N
        getContentPane().add(jLabelFundoPrincipal);
        jLabelFundoPrincipal.setBounds(0, 0, 820, 500);

        jMenuAjuda.setText("Ajuda");
        jMenuBar1.add(jMenuAjuda);

        jMenuSair.setText("Sair");

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemSair);

        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(828, 548));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddProfessorActionPerformed
        TelaAddProfessor telaAddProf = new TelaAddProfessor();
        telaAddProf.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonAddProfessorActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        TelaLogin telasair = new TelaLogin();
        telasair.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jButtonAlterarProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarProfessorActionPerformed
        // TODO add your handling code here:
        int codigo= Integer.parseInt(nome);
        new TelaEditarProfessor(codigo).setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonAlterarProfessorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new TelaDescricao().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelecionarActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        if (jTableDocente.getSelectedRow() >= 0) {
            nome = "" + jTableDocente.getModel().getValueAt(jTableDocente.getSelectedRow(), 0);
            docenteDAO.acessaTabela(docente, Integer.parseInt(nome));
            System.out.println(nome);
            jButtonAlterarProfessor.setEnabled(true);
            jButtonRemoverProfessor.setEnabled(true);

        }
    }//GEN-LAST:event_jButtonSelecionarActionPerformed

    private void jButtonRemoverProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverProfessorActionPerformed
        // TODO add your handling code here:
        String message = "Voce deseja realmente  excluir?";

        int reply = JOptionPane.showConfirmDialog(null, message, "", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            docenteDAO.excluir(Integer.parseInt(nome));
            new TelaPrincipal().setVisible(true);
            dispose();
        }


    }//GEN-LAST:event_jButtonRemoverProfessorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAddProfessor;
    private javax.swing.JButton jButtonAlterarProfessor;
    private javax.swing.JButton jButtonRemoverProfessor;
    private javax.swing.JButton jButtonSelecionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFundoPrincipal;
    private javax.swing.JMenu jMenuAjuda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemSair;
    private static javax.swing.JMenu jMenuSair;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDocente;
    // End of variables declaration//GEN-END:variables
}
