/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author MARCOS
 */
public class TelaProfessor extends javax.swing.JFrame {

    /**
     * Creates new form TelaProfessor
     */
    public TelaProfessor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonAtividade1 = new javax.swing.JButton();
        jButtonAtividade2 = new javax.swing.JButton();
        jButtonAtividade3 = new javax.swing.JButton();
        jButtonNovaAtividade = new javax.swing.JButton();
        jButtonAlterarAtividade = new javax.swing.JButton();
        jButtonRemoverAtividade = new javax.swing.JButton();
        jLabelTituloProf = new javax.swing.JLabel();
        jButtonAtividade4 = new javax.swing.JButton();
        jButtonAtividade5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabelFundoLogin = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAjudaProf = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuSairProf = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButtonAtividade1.setText("Atividade 1");
        jButtonAtividade1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtividade1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAtividade1);
        jButtonAtividade1.setBounds(70, 90, 130, 40);

        jButtonAtividade2.setText("Atividade 2");
        getContentPane().add(jButtonAtividade2);
        jButtonAtividade2.setBounds(70, 160, 130, 40);

        jButtonAtividade3.setText("Atividade 5");
        jButtonAtividade3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtividade3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAtividade3);
        jButtonAtividade3.setBounds(270, 160, 130, 40);

        jButtonNovaAtividade.setBackground(new java.awt.Color(0, 153, 0));
        jButtonNovaAtividade.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonNovaAtividade.setText("Nova Atividade");
        jButtonNovaAtividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovaAtividadeActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNovaAtividade);
        jButtonNovaAtividade.setBounds(120, 380, 130, 50);

        jButtonAlterarAtividade.setBackground(new java.awt.Color(255, 102, 0));
        jButtonAlterarAtividade.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonAlterarAtividade.setText("Alterar Atividade");
        jButtonAlterarAtividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarAtividadeActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAlterarAtividade);
        jButtonAlterarAtividade.setBounds(300, 380, 130, 50);

        jButtonRemoverAtividade.setBackground(new java.awt.Color(255, 0, 0));
        jButtonRemoverAtividade.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonRemoverAtividade.setText("Remover Atividade");
        getContentPane().add(jButtonRemoverAtividade);
        jButtonRemoverAtividade.setBounds(470, 380, 150, 50);

        jLabelTituloProf.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabelTituloProf.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTituloProf.setText("Gereciamento de Atividades - RIT");
        getContentPane().add(jLabelTituloProf);
        jLabelTituloProf.setBounds(60, 10, 360, 60);

        jButtonAtividade4.setText("Atividade 3");
        getContentPane().add(jButtonAtividade4);
        jButtonAtividade4.setBounds(70, 230, 130, 40);

        jButtonAtividade5.setText("Atividade 4");
        jButtonAtividade5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtividade5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAtividade5);
        jButtonAtividade5.setBounds(270, 90, 130, 40);

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Gerar Relatório");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(590, 30, 130, 40);

        jLabelFundoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoficial.png"))); // NOI18N
        getContentPane().add(jLabelFundoLogin);
        jLabelFundoLogin.setBounds(0, 0, 750, 530);

        jMenuAjudaProf.setText("Opções");

        jMenuItem1.setText("Voltar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuAjudaProf.add(jMenuItem1);

        jMenuBar1.add(jMenuAjudaProf);

        jMenuSairProf.setText("Sair");

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuSairProf.add(jMenuItemSair);

        jMenuBar1.add(jMenuSairProf);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(763, 628));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNovaAtividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovaAtividadeActionPerformed
        TelaDescricao teladd1 = new TelaDescricao();
        teladd1.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonNovaAtividadeActionPerformed

    private void jButtonAtividade1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtividade1ActionPerformed
        TelaAtividade1 tela1 = new TelaAtividade1();
        tela1.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonAtividade1ActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        TelaLogin telasair1 = new TelaLogin ();
        telasair1.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        TelaPrincipal telavoltarprof = new TelaPrincipal ();
        telavoltarprof.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButtonAlterarAtividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarAtividadeActionPerformed
        TelaAtividade1 teladd2 = new TelaAtividade1();
        teladd2.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonAlterarAtividadeActionPerformed

    private void jButtonAtividade3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtividade3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAtividade3ActionPerformed

    private void jButtonAtividade5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtividade5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAtividade5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaProfessor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAlterarAtividade;
    private javax.swing.JButton jButtonAtividade1;
    private javax.swing.JButton jButtonAtividade2;
    private javax.swing.JButton jButtonAtividade3;
    private javax.swing.JButton jButtonAtividade4;
    private javax.swing.JButton jButtonAtividade5;
    private javax.swing.JButton jButtonNovaAtividade;
    private javax.swing.JButton jButtonRemoverAtividade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFundoLogin;
    private javax.swing.JLabel jLabelTituloProf;
    private javax.swing.JMenu jMenuAjudaProf;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenu jMenuSairProf;
    // End of variables declaration//GEN-END:variables
}
