/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author MARCOS
 */
public class TelaDescricao extends javax.swing.JFrame {

    /**
     * Creates new form TelaDescricaoRit
     */
    public TelaDescricao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelInfoRit = new javax.swing.JLabel();
        jLabelDisciplinas = new javax.swing.JLabel();
        jComboBoxDisciplinas = new javax.swing.JComboBox<>();
        jLabelAlunosOrientados = new javax.swing.JLabel();
        jRadioButtonAlunosGraduacao = new javax.swing.JRadioButton();
        jRadioButtonAlunosIniciacao = new javax.swing.JRadioButton();
        jRadioButtonAlunosMestrado = new javax.swing.JRadioButton();
        jRadioButtonAlunosDoutorado = new javax.swing.JRadioButton();
        jLabelArtigosPub = new javax.swing.JLabel();
        jButtonUploadArtigo = new javax.swing.JButton();
        jLabelAtivCoord = new javax.swing.JLabel();
        jTextFieldDescAtividadeCoord = new javax.swing.JTextField();
        jLabelFundoDescricao = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAjudaProf = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuSairProf = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabelInfoRit.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabelInfoRit.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInfoRit.setText("Informações Relatório Individual de Trabalho - RIT");
        getContentPane().add(jLabelInfoRit);
        jLabelInfoRit.setBounds(40, 20, 490, 40);

        jLabelDisciplinas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelDisciplinas.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDisciplinas.setText("Disciplinas:");
        getContentPane().add(jLabelDisciplinas);
        jLabelDisciplinas.setBounds(60, 80, 90, 40);

        jComboBoxDisciplinas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<< Selecione uma das opções >>", "Arquitetura de Computares", "Algoritmos e Estruturas de Dados I", "Algoritmos e Estruturas de Dados II", "Análise e Projetos de Sistemas", "Avaliação de Desempenho", "Banco de Dados I", "Computação Númerica", "Compiladores", "Empreendedorismo em Informática", "Introdução a Computação", "Introdução a Engenharia de Software", "Introdução a Teoria de Grafos", "Inteligência Artificial ", "Introdução a Computação Gráfica", "Interação Humano-Computador", "Informática Ética e Sociedade", "Laboratório de Programção Avançada", "Linguagem Formais e Automatos", "Matemática Discreta", "Metodologia Cientifica em Ciência da Computação", "Organização de Computadores", "Paradigmas de Linguagem de Programação", "Projeto e Análise de Algoritmos", "Programação Web", "Redes de Computadores", "Sistemas Lógicos", "Sistemas Operacionais", "Técnicas Avançadas de Programação", "Textos Técnicos em Ciencia da Computação " }));
        jComboBoxDisciplinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDisciplinasActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxDisciplinas);
        jComboBoxDisciplinas.setBounds(150, 90, 290, 20);

        jLabelAlunosOrientados.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelAlunosOrientados.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAlunosOrientados.setText("Alunos Orientados:");
        getContentPane().add(jLabelAlunosOrientados);
        jLabelAlunosOrientados.setBounds(60, 130, 140, 30);

        jRadioButtonAlunosGraduacao.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonAlunosGraduacao.setText("Alunos de Graduação - TCC");
        jRadioButtonAlunosGraduacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAlunosGraduacaoActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonAlunosGraduacao);
        jRadioButtonAlunosGraduacao.setBounds(180, 130, 180, 23);

        jRadioButtonAlunosIniciacao.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonAlunosIniciacao.setText("Alunos de Graduação - Iniciação Científica");
        getContentPane().add(jRadioButtonAlunosIniciacao);
        jRadioButtonAlunosIniciacao.setBounds(180, 170, 260, 23);

        jRadioButtonAlunosMestrado.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonAlunosMestrado.setText("Alunos de Mestrado");
        getContentPane().add(jRadioButtonAlunosMestrado);
        jRadioButtonAlunosMestrado.setBounds(180, 210, 180, 23);

        jRadioButtonAlunosDoutorado.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonAlunosDoutorado.setText("Alunos de Doutorado");
        getContentPane().add(jRadioButtonAlunosDoutorado);
        jRadioButtonAlunosDoutorado.setBounds(180, 250, 180, 23);

        jLabelArtigosPub.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelArtigosPub.setForeground(new java.awt.Color(255, 255, 255));
        jLabelArtigosPub.setText("Artigos Publicados:");
        getContentPane().add(jLabelArtigosPub);
        jLabelArtigosPub.setBounds(60, 300, 140, 30);

        jButtonUploadArtigo.setText("Faça o upload");
        jButtonUploadArtigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUploadArtigoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonUploadArtigo);
        jButtonUploadArtigo.setBounds(190, 300, 170, 30);

        jLabelAtivCoord.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelAtivCoord.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAtivCoord.setText("Atividades de Coordenação:");
        getContentPane().add(jLabelAtivCoord);
        jLabelAtivCoord.setBounds(60, 360, 190, 20);

        jTextFieldDescAtividadeCoord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDescAtividadeCoordActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldDescAtividadeCoord);
        jTextFieldDescAtividadeCoord.setBounds(240, 360, 310, 130);

        jLabelFundoDescricao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoficial.png"))); // NOI18N
        getContentPane().add(jLabelFundoDescricao);
        jLabelFundoDescricao.setBounds(-20, 0, 650, 710);

        jMenuAjudaProf.setText("Opções");

        jMenuItem1.setText("Voltar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuAjudaProf.add(jMenuItem1);

        jMenuBar1.add(jMenuAjudaProf);

        jMenuSairProf.setText("Sair");

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuSairProf.add(jMenuItemSair);

        jMenuBar1.add(jMenuSairProf);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxDisciplinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDisciplinasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxDisciplinasActionPerformed

    private void jRadioButtonAlunosGraduacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAlunosGraduacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonAlunosGraduacaoActionPerformed

    private void jButtonUploadArtigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUploadArtigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUploadArtigoActionPerformed

    private void jTextFieldDescAtividadeCoordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDescAtividadeCoordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDescAtividadeCoordActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        TelaProfessor telavoltarprof = new TelaProfessor ();
        telavoltarprof.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        TelaLogin telasair1 = new TelaLogin ();
        telasair1.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDescricao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDescricao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDescricao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDescricao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDescricao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonUploadArtigo;
    private javax.swing.JComboBox<String> jComboBoxDisciplinas;
    private javax.swing.JLabel jLabelAlunosOrientados;
    private javax.swing.JLabel jLabelArtigosPub;
    private javax.swing.JLabel jLabelAtivCoord;
    private javax.swing.JLabel jLabelDisciplinas;
    private javax.swing.JLabel jLabelFundoDescricao;
    private javax.swing.JLabel jLabelInfoRit;
    private javax.swing.JMenu jMenuAjudaProf;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenu jMenuSairProf;
    private javax.swing.JRadioButton jRadioButtonAlunosDoutorado;
    private javax.swing.JRadioButton jRadioButtonAlunosGraduacao;
    private javax.swing.JRadioButton jRadioButtonAlunosIniciacao;
    private javax.swing.JRadioButton jRadioButtonAlunosMestrado;
    private javax.swing.JTextField jTextFieldDescAtividadeCoord;
    // End of variables declaration//GEN-END:variables
}
