/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author MARCOS
 */
public class TelaAddProfessor extends javax.swing.JFrame {

    /**
     * Creates new form TelaDadosProfessor
     */
    public TelaAddProfessor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTituloDadosProf = new javax.swing.JLabel();
        jLabelSexoProf = new javax.swing.JLabel();
        jLabelAddCodigoProf = new javax.swing.JLabel();
        jLabelAddEmailProf = new javax.swing.JLabel();
        jLabelAddTelefoneProf = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButtonAddProfessor = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButtonVoltar = new javax.swing.JButton();
        jLabelNomeProf = new javax.swing.JLabel();
        jRadioButtonSexoMasc = new javax.swing.JRadioButton();
        jRadioButtonSexoFem = new javax.swing.JRadioButton();
        jTextField5 = new javax.swing.JTextField();
        jLabelEnderecoProf = new javax.swing.JLabel();
        jLabelFundoDadosProf = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuSairProf = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabelTituloDadosProf.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabelTituloDadosProf.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTituloDadosProf.setText("Dados");
        getContentPane().add(jLabelTituloDadosProf);
        jLabelTituloDadosProf.setBounds(60, 20, 200, 50);

        jLabelSexoProf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelSexoProf.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSexoProf.setText("Sexo:");
        getContentPane().add(jLabelSexoProf);
        jLabelSexoProf.setBounds(510, 110, 50, 30);

        jLabelAddCodigoProf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelAddCodigoProf.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAddCodigoProf.setText("SIAPE:");
        getContentPane().add(jLabelAddCodigoProf);
        jLabelAddCodigoProf.setBounds(60, 160, 80, 30);

        jLabelAddEmailProf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelAddEmailProf.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAddEmailProf.setText("E-mail:");
        getContentPane().add(jLabelAddEmailProf);
        jLabelAddEmailProf.setBounds(60, 210, 60, 30);

        jLabelAddTelefoneProf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelAddTelefoneProf.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAddTelefoneProf.setText("Telefone:");
        getContentPane().add(jLabelAddTelefoneProf);
        jLabelAddTelefoneProf.setBounds(60, 260, 100, 40);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(140, 110, 330, 30);

        jButtonAddProfessor.setBackground(new java.awt.Color(0, 153, 0));
        jButtonAddProfessor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonAddProfessor.setText("Salvar");
        jButtonAddProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddProfessorActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAddProfessor);
        jButtonAddProfessor.setBounds(430, 410, 110, 50);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(140, 160, 250, 30);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(140, 210, 250, 30);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(140, 260, 250, 30);

        jButtonVoltar.setBackground(new java.awt.Color(255, 102, 0));
        jButtonVoltar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltar);
        jButtonVoltar.setBounds(290, 410, 110, 50);

        jLabelNomeProf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNomeProf.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNomeProf.setText("Nome:");
        getContentPane().add(jLabelNomeProf);
        jLabelNomeProf.setBounds(60, 100, 90, 40);

        jRadioButtonSexoMasc.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonSexoMasc.setText("Masculino");
        getContentPane().add(jRadioButtonSexoMasc);
        jRadioButtonSexoMasc.setBounds(570, 110, 100, 23);

        jRadioButtonSexoFem.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonSexoFem.setText("Feminino");
        getContentPane().add(jRadioButtonSexoFem);
        jRadioButtonSexoFem.setBounds(690, 110, 93, 23);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(140, 320, 280, 30);

        jLabelEnderecoProf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelEnderecoProf.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEnderecoProf.setText("Endereço:");
        getContentPane().add(jLabelEnderecoProf);
        jLabelEnderecoProf.setBounds(60, 320, 90, 40);

        jLabelFundoDadosProf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoficial.png"))); // NOI18N
        getContentPane().add(jLabelFundoDadosProf);
        jLabelFundoDadosProf.setBounds(30, 0, 820, 570);

        jMenuSairProf.setText("Sair");

        jMenuItemSair.setText("Sair");
        jMenuSairProf.add(jMenuItemSair);

        jMenuBar1.add(jMenuSairProf);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddProfessorActionPerformed
        TelaPrincipal tela = new TelaPrincipal();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonAddProfessorActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
         TelaPrincipal telaVoltar = new TelaPrincipal();
        telaVoltar.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAddProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAddProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAddProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAddProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAddProfessor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddProfessor;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabelAddCodigoProf;
    private javax.swing.JLabel jLabelAddEmailProf;
    private javax.swing.JLabel jLabelAddTelefoneProf;
    private javax.swing.JLabel jLabelEnderecoProf;
    private javax.swing.JLabel jLabelFundoDadosProf;
    private javax.swing.JLabel jLabelNomeProf;
    private javax.swing.JLabel jLabelSexoProf;
    private javax.swing.JLabel jLabelTituloDadosProf;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenu jMenuSairProf;
    private javax.swing.JRadioButton jRadioButtonSexoFem;
    private javax.swing.JRadioButton jRadioButtonSexoMasc;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
